<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Bibliotex 3 </title>
<link rel="stylesheet" type="text/css" href="assets/view.css" media="all">
<script type="text/javascript" src="assets/view.js"></script>
<script type="text/javascript" src="assets/calendar.js"></script>
</head>
<body id="main_body" >
	
	<img id="top" src="assets/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Bibliotex 3 </a></h1>
		<form id="form_363808" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Bibliotex 3 </h2>
			<p>Cadastro de Obras</p>
		</div>						
			<ul >
			
		<li id="li_1" >
		<label class="description" for="element_1">Título </label>
		<div>
			<input id="title" name="title" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		
		
		<li id="li_2" >
		<label class="description" for="element_2">Autor </label>
		<div>
			<input id="author" name="author" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		
		<li id="li_3" >
		<label class="description" for="element_3">Data de Publicação </label>
		<span>
			<input id="element_3_1" name="element_3_1" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="element_3_1">DD</label>
		</span>
		<span>
			<input id="element_3_2" name="element_3_2" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="element_3_2">MM</label>
		</span>
		<span>
	 		<input id="element_3_3" name="element_3_3" class="element text" size="4" maxlength="4" value="" type="text">
			<label for="element_3_3">YYYY</label>
		</span>
	
		<span id="calendar_3">
			<img id="cal_img_3" class="datepicker" src="assets/calendar.gif" alt="Pick a date.">	
		</span>
		<script type="text/javascript">
			Calendar.setup({
			inputField	 : "element_3_3",
			baseField    : "element_3",
			displayArea  : "calendar_3",
			button		 : "cal_img_3",
			ifFormat	 : "%B %e, %Y",
			onSelect	 : selectEuropeDate
			});
		</script>
		<p class="guidelines" id="guide_3"><small>DD/MM/YYYY</small></p> 
		</li>		<li id="li_4" >
		
		<label class="description" for="element_4">Número de Páginas </label>
		<div>
			<input id="pages" name="pages" class="element text small" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_5" >
		<label class="description" for="element_5">Conteúdo </label>
		<div>
			<textarea id="content" name="content" class="element textarea large"></textarea> 
		</div> 
		</li>
		
		<li id="li_6" >
		<label class="description" for="element_6">Tipo </label>
		<div>
		<select class="element select medium" id="type" name="type"> 
			<option value="" selected="selected"></option>
<option value="1" >Livro</option>
<option value="2" >Revista</option>
<option value="3" >Artigo</option>

		</select>
		</div> 
		</li>
		
		
		
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="363808" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="assets/bottom.png" alt="">
	</body>
</html>

<?php


	require_once 'Book.php';
	//Refactory: transformar em uma funcao
	session_start();
	if ( $_SESSION[auth]=""){
	
	error_log("Bibliotex: Something wrong with your session, go back to index... ", 0 );
	
	header('Location: index.php');
	exit;
	
	
	} else {
		error_log("Bem vindo   ".$_SESSION['username'], 0 );
	
		print 'Bem vindo '. $_SESSION['username'];
			
	}
	
	
 	$newBook = new Book();
 	//TODO incluir a data
 	$newBook->addBook($_POST["title"], $_POST["author"],  $_POST["pages"], $_POST["content"], $_POST["type"]);


?>