<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Bibliotex 3 </title>
<link rel="stylesheet" type="text/css" href="assets/view.css" media="all">
<script type="text/javascript" src="assets/view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="assets/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Bibliotex 3 </a></h1>
		<form id="form_363808" class="appnitro"  method="post" action="newUser.php">
					<div class="form_description">
			<h2>Bibliotex 3 </h2>
			<p>Novo Usu‡rio</p>
		</div>						
			<ul >
			
					<li id="li_4" >
		<label class="description" for="element_4">Email </label>
		<div>
			<input id="element_4" name="mail" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_1" >
		<label class="description" for="element_1">Usu‡rio </label>
		<div>
			<input id="element_1" name="username" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Senha </label>
		<div>
			<input id="element_2" name="password" class="element text medium" type="password" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_5" >
		<label class="description" for="element_5">Confirmar Senha </label>
		<div>
			<input id="element_5" name="password2" class="element text medium" type="password" maxlength="255" value=""/> 
		</div> 
		</li>		
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="363808" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="assets/bottom.png" alt="">
	</body>
</html>

<!--  
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    </head>
    <body>
      New User<br>
        <form action="newUser.php" method="POST">
            Username: <input type="text" name="username"/><br/>
            E-mail: <input type="text" name="mail"/><br/>
            
            Password: <input type="password" name="password"/><br/>
            Please confirm your password: <input type="password" name="password2"/><br/>
            <input type="submit" value="Register"/>
        </form>
     </body>
</html>
-->
<?php 
require_once 'User.php';
	

	//TODO: teria que fazer essa verificacao no formulario mesmo
	if ($_POST["password"]=="" || $_POST["password2"]=="" || $_POST["username"]=="" || $_POST["mail"]==""){
		exit;
	} 
    	
	if ($_POST["password2"]=="")
    	$password2IsEmpty = true;
	if ($_POST["password"]!=$_POST["password2"]) {
    	$passwordIsValid = false;
	}
//"nome", "zeh@cpovo.net", "aluno", "apple"
	$user = new User();
	$result= $user->createUser($_POST["username"], $_POST["mail"], "aluno", $_POST["password"]);
	
	
	//After the user creation redirect to main page
	if ($result){
			error_log("Logando novo usuario ".$result, 0 );
		
        	$_SESSION['username'] = $_POST['username'];
        	header('Location: bibliotex.php');
        	exit;
	}
	
	
    ?>